### ISSUE TITLE
Country Capital

### ISSUE THREAD

**Issue by Xmk** [nevadskiy/laravel-geonames#11]
В странах столица хранится в бд в виде строки, может было бы правильнее и удобнее хранить ее в виде связи с объектом города?

**Comment by nevadskiy** [comment]
@Xmk да, есть такая проблема. 

Если хранить cтолицу в виде внешнего ключа с таблицы countries, то получится циклическая зависимость (Circular Reference) между таблицами: countries: capital_id -> <- cities: country_id.

Из-за нее, например, не получится вообще вставлять данные в любую из этих таблиц.
Поэтому, для простоты, оставил столицу в виде строки, как в оригинальных таблицах Geonames.

Если же действительно в проекте нужна связь на город столицу, то можно вручную создать дополнительную таблицу `countries_capitals` и в ней уже объявить ключи `country_id` и `city_id`.

**Comment by Xmk** [comment]
@nevadskiy в основной пакет не будешь делать такую связку?
