### ISSUE TITLE
Timezone ID

### ISSUE THREAD

**Issue by Xmk** [nevadskiy/laravel-geonames#12]
Сейчас на всех объектах timezone указан строковым идентификатором (_Europe\Moscow_).
Я считаю что правильнее было бы собрать все timezones в отдельную таблицу и создать связи со всеми объектами по внутреннему ID.
Как считаешь?

**Comment by nevadskiy** [comment]
@Xmk В PHP уже есть встроенная база данных с этими таймзонами (https://pecl.php.net/package/timezonedb).
А стандартная библиотека для работы с датами легко умеет создавать объекты таймзоны по этим строковым идентификаторам. Поэтому не вижу смысла создавать для них еще одну таблицу.
