### ISSUE TITLE
php artisan geonames:insert --reset с ошибкой из-за ключей

### ISSUE THREAD

**Issue by mazhurnyy** [nevadskiy/laravel-geonames#16]
При запуске команды 
php artisan geonames:insert --reset
- ошибка, невозможно очистить таблицу из-за ограничения ключей

Решение временно отключаем проверку ключей 
в файле InsertCommand  добавить 
public function handle() {
Schema::disableForeignKeyConstraints();
.....
Schema::enableForeignKeyConstraints();
}

при добавлении России в таблице countries поле area(double(10, 2)) не достаточно, не помещается значение
 увеличить поле area(double(12, 2))

**Comment by mazhurnyy** [comment]
еще баг при работе

было
   public function handle(LocaleUpdated $event): void
    {
            $this->translator->setLocale(
                $event->locale
            );
    }

при работе, если вызвать метод setLocale  - ошибка  $event->locale = null (недопустимо) нужна строка

решение:
   public function handle(LocaleUpdated $event): void
    {
        if(!is_null($event->locale)){
            $this->translator->setLocale(
                $event->locale
            );
        }
    }

**Comment by nevadskiy** [comment]
@mazhurnyy спасибо за репорты. Как будет время, обязательно посмотрю.
