### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'elevation' at row 521

### ISSUE THREAD

**Issue by hoektoe** [nevadskiy/laravel-geonames#26]
Tried seeding and keep getting error above. Changed the model etc to be bigint and still giving issues.

"SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'elevation' at row 521"

Seems this entry, 5 column is elevation is stopping the insert, which is confusing since 1868 isn't bug
`  (130, 2022-08-31 19:08:21, 1868, 1745, 1868, PPL, 1232783, 6.97078, 80.78286, Nuwara Eliya, 27500, Asia/Colombo, 2022-01-10 00:00:00)`

and then row 521 is

` (119, 2022-08-31 19:08:16, -9999, 1619, ?, PPL, 1091117, -12.15667, 44.40806, Mirontsi, 10168, Indian/Comoro, 2020-06-14 00:00:00),
`

**Comment by hoektoe** [comment]
Ah looks like actually breaking for division_id as -9999 ?

**Comment by nevadskiy** [comment]
@hoektoe have you tried running on mysql?

**Comment by Xmk** [comment]
for example
https://www.geonames.org/5854936/kingman-reef.html
have elevation -3

impossible, because:
https://github.com/nevadskiy/laravel-geonames/blob/master/stubs/database/migrations/2020_06_06_200000_create_countries_table.stub#L37
elevation field have unsigned attribute

**Comment by renitreni** [comment]
Hi,

This issue still not resolved. Please see error below when running on mysql.
![Uploading Screenshot 2024-07-24 at 8.32.13 AM.png…]()

**Comment by nevadskiy** [comment]
Fixed in #41
