### ISSUE TITLE
Adding more Geonames Feature codes 

### ISSUE THREAD

**Issue by nesmrtelny** [nevadskiy/laravel-geonames#33]
Hi there,

I'm using your fantastic package and would like to ask you for adding (or pointing out if there is already some possible solution without changing the package) more Geonames Feature codes. Currently the package supports codes like these: 

- PPL
- PPL...
- ADM1
- ADM2   

However, I need also support for other codes like:

- PARK
- MT
- HLL

_More listed here: [http://www.geonames.org/export/codes.html ↗](http://www.geonames.org/export/codes.html)_

I have tried to extend CitySeeder (adding new codes into array $featureCodes), but it does not seem work even with updated filter method.

My code from /database/seeders/Geo/CitySeeder.php:
```php
<?php

namespace Database\Seeders\Geo;

use App\Models\Geo\City;
use Illuminate\Database\Eloquent\Model;
use Nevadskiy\Geonames\Seeders\CitySeeder as Seeder;

class CitySeeder extends Seeder
{
    protected static $model = City::class;

    protected $minPopulation = 5000;

    /**
     * The allowed feature codes.
     *
     * @var array
     */
    protected $featureCodes = [
        FeatureCode::PPL,
        FeatureCode::PPLC,
        FeatureCode::PPLA,
        FeatureCode::PPLA2,
        FeatureCode::PPLA3,
        FeatureCode::PPLS,
        FeatureCode::MT,
        FeatureCode::HLL,
    ];

    /**
     * Get a new country model instance.
     */
    protected function newCountryModel(): Model
    {
        return CountrySeeder::newModel();
    }

    /**
     * Get a new division model instance.
     */
    protected function newDivisionModel(): Model
    {
        return DivisionSeeder::newModel();
    }

    protected function filter(array $record): bool
    {
        // Change filter to accept also hills and mountains
        if (
            // cities above given minPopulation
            (
                in_array($record['feature code'], $this->featureCodes, true)
                &&
                strpos($record['feature code'], 'PPL') !== false
                &&
                $record['population'] >= $this->minPopulation
            )
            ||
            // or mountains and hills - minPopulation is irelevant
            in_array($record['feature code'], ['MT', 'HLL'])
        ) {
            return true;
        } else {
            return false;
        }
    }
}
```

Adding support for more Feature codes would make this package even more useful and flexible.

Thank you for creating and maintaining this great package.

Wishes,
Pavel

**Comment by nevadskiy** [comment]
Hi @nesmrtelny. Unfortunately, currently have no time to look into it. It should work fine from what I see on the provided code. The only place where cities can be filtered is that `filter` method.

**Comment by nevadskiy** [comment]
I also have an app that uses custom feature codes and there is no problem. So I do not even know what to recommend in this case...

**Comment by nesmrtelny** [comment]
Thank you @nevadskiy for the response and confirmation the provided code should work. I will test it again and I am closing the Issue. Cheers!
