### ISSUE TITLE
[Bug Fix] Migration Cities - SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'elevation'

### ISSUE THREAD

**Issue by renitreni** [nevadskiy/laravel-geonames#40]
I got an error when running **_php artisan geonames:seed_** 

![Screenshot 2024-07-24 at 8 32 13 AM](https://github.com/user-attachments/assets/a601f317-c3eb-4fc5-abf2-ea79488118f4)

If possible, can you assign this to me and I will fix the migration for elevation column.

**Comment by nevadskiy** [comment]
@renitreni yes sure feel free to submit a PR

**Comment by renitreni** [comment]
@nevadskiy need your review on this PR.
https://github.com/nevadskiy/laravel-geonames/pull/41

**Comment by nevadskiy** [comment]
@renitreni thanks a lot. merged and released in 0.6.1
