### ISSUE TITLE
Don't work without NOVA

### ISSUE THREAD

**Issue by Xmk** [nevadskiy/laravel-geonames#5]
Class 'Laravel\Nova\Nova' not found

**Comment by nevadskiy** [comment]
@Xmk 

Yes, i just test it with Nova, thanks for the issue. Fix soon!

**Comment by nevadskiy** [comment]
@Xmk fixed. 
Try 0.1.1 version.

**Comment by nevadskiy** [comment]
If you face any problems again, feel free to open another issue.

**Comment by Xmk** [comment]
> 
> 
> @Xmk fixed.
> Try 0.1.1 version.

спасибо за труды, после длительных поисков я нашел лучший пакет базы geonames для laravel :)

**Comment by nevadskiy** [comment]
@Xmk не за что :)
Вчера только опубликовал первую версию. На данный момент все еще очень сырое, поэтому может быть с этим напряг. Постараюсь в ближайшем будущем добавить больше возможностей для кастомизации и дописать доку. Также может как-то постараюсь ускорить процесс сидинга данных, а то сейчас, чтобы все накатить, моем компу нужно около 12 минут (без учета скачивания архива).

**Comment by Xmk** [comment]
@nevadskiy буквально перед тем как я нашел твой пакет я поставил другой, он сидил 6 часов...
