### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by MikadoInfo** [nevadskiy/laravel-geonames#9]
I got this error when i tried to install the package with composer

![error package](https://user-images.githubusercontent.com/69799889/112815500-ab5acb80-9080-11eb-8e8b-309813a3b142.png)

**Comment by nevadskiy** [comment]
Hi @MikadoInfo!

Try to clear your config cache using command `php artisan config:clear` and install again.

**Comment by MikadoInfo** [comment]
Thank you it worked

**Comment by nevadskiy** [comment]
@MikadoInfo you are welcome. If you have any wished for the package, write them here, I will consider implementing them.
